[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x6e6a86"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "0x524f67"
text = "0xe0def4"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x26233a"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
# background = "#0a0a0a"
background = "#060615"

[colors.selection]
background = "0x403d52"
text = "0xe0def4"

[colors.vi_mode_cursor]
cursor = "0x524f67"
text = "0xe0def4"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.offset]
y = -3

[font.bold]
family = "Lilex Nerd Font Mono"

[font.italic]
family = "Lilex Nerd Font Mono"

[font.normal]
# family = "SeriousShanns Nerd Font Mono"
# family = "Monaco"
# family = "Recursive Mono Linear Static"
family = "Lilex Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.94

# [window.dimensions]
# columns = 80
# lines = 24

[window.padding]
x = 5
y = 1

[general]
live_config_reload = true


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
