#!/usr/bin/env bash

HOST="8.8.8.8"; URL="https://example.com/"

if ! ping -c1 -W1 "$HOST" &>/dev/null; then
  echo "<span foreground='red'></span>"
  exit
fi

if ! curl -Is --max-time 2 "$URL" &>/dev/null; then
  echo "<span foreground='red'></span>"
  exit
fi

# Green check
echo ""
