#!/bin/bash
TEMP_DEVICE="${BLOCK_INSTANCE:-CPU}"

# Find sensors using which
SENSORS_CMD=$(which sensors 2>/dev/null)
if [ -z "$SENSORS_CMD" ]; then
  echo "N/A"
  exit 0
fi

TEMP_OUTPUT=$($SENSORS_CMD | grep "${TEMP_DEVICE}")

# Exit if no temperature data found
if [ -z "$TEMP_OUTPUT" ]; then
  echo "N/A"
  exit 0
fi

IS_URGENT=0

TOTAL_TEMP=0
TOTAL_COUNT=0
while read RESULT_LINE; do
  TOTAL_COUNT=$((TOTAL_COUNT +1))
  CURRENT_TEMP=$(echo "${RESULT_LINE}" | grep -o -E "[\+\-]?[0-9]*\.[0-9]*°C" | sed -n '1p' | tr -d '+°C')
  TOTAL_TEMP=$(echo "scale=2;${TOTAL_TEMP}+${CURRENT_TEMP}" | /usr/bin/bc -l)
done <<< "$(echo -e "$TEMP_OUTPUT")"

AVERAGE_TEMP=$(echo "scale=0;${TOTAL_TEMP}/${TOTAL_COUNT}" | /usr/bin/bc -l)

if [[ "${TOTAL_COUNT}" -gt 1 ]]; then
  AVERAGE_TEMP="${AVERAGE_TEMP}"
fi

echo "${AVERAGE_TEMP}°C"
echo ""

if [[ "${IS_URGENT}" -eq 1 ]]; then
  exit 33
fi
