# Each block command defaults to the script name to avoid boilerplate.
command=~/.config/i3/scripts/$BLOCK_NAME
separator_block_width=30

[start_divider]
full_text=​

[pomo]
command=~/Development/pomodoro/pomo_state.py
interval=1

[audio]
label=
interval=1
color=#e9edc9

[cpu]
label=
interval=3
min_width=50

[temperature]
instance=CPU
label=
interval=5

[network]
label=
instance=wlp2s0
interval=10

[i3speedtest]
label=
interval=2
markup=pango

[space]
label=
interval=30
color=#c3d3b3

[memory]
label=
instance=mem;free
interval=50
color=#c3d3b3

[weather]
instance=4460162
interval=60

[battery]
label=
instance=0
interval=5

[time]
label= 
command=date '+%a %b %d, %H:%M:%S  '
interval=1

